--
-- PostgreSQL database dump
--

\restrict 44HcXhuJzHvgqYdBVqEII0WQtb3FPXixjr5OUes2cbRGa8cBYl7A4I90GKBqogT

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: survey_response; Type: TABLE; Schema: public; Owner: sathwik
--

CREATE TABLE public.survey_response (
    id bigint NOT NULL,
    comments character varying(255),
    email character varying(255),
    platform character varying(255),
    rating integer NOT NULL
);


ALTER TABLE public.survey_response OWNER TO sathwik;

--
-- Name: survey_response_id_seq; Type: SEQUENCE; Schema: public; Owner: sathwik
--

ALTER TABLE public.survey_response ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: survey_response; Type: TABLE DATA; Schema: public; Owner: sathwik
--

COPY public.survey_response (id, comments, email, platform, rating) FROM stdin;
1		satwik.sharma792@gmail.com	Docker	1
2	ons	shravya2302@gmail.com	Docker	1
3	ons	shravya2302@gmail.com	Docker	1
\.


--
-- Name: survey_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sathwik
--

SELECT pg_catalog.setval('public.survey_response_id_seq', 3, true);


--
-- Name: survey_response survey_response_pkey; Type: CONSTRAINT; Schema: public; Owner: sathwik
--

ALTER TABLE ONLY public.survey_response
    ADD CONSTRAINT survey_response_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 44HcXhuJzHvgqYdBVqEII0WQtb3FPXixjr5OUes2cbRGa8cBYl7A4I90GKBqogT

