[web]
target_node ansible_host=192.168.29.29

[all:vars]
ansible_user=ansibleadmin
ansible_ssh_private_key_file=~/.ssh/ansible_key
# THIS IS THE KEY: We force the VM to use its Python 3.12 
# but we tell Ansible to stop looking for the 'six' library
ansible_python_interpreter=/usr/bin/python3
