apiVersion: v1
kind: PersistentVolume
metadata:
  name: survey-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/survey-storage" # Updated path for better visibility in Minikube
  persistentVolumeReclaimPolicy: Retain # Ensures data stays even if PVC is deleted
