apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: survey-pvc
  namespace: prod
spec:
  storageClassName: "" # ADD THIS LINE: It tells K8s NOT to use the default 'standard' class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
