apiVersion: v1
kind: Service
metadata:
  name: survey-external-service
spec:
  type: NodePort
  selector:          #This is service scanner
    app: survey      #This is secret sauce
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002  # You can pick a port between 30000-32767
