---
- name: Deploy Professional Nginx
  hosts: web
  become: true
  
  pre_tasks:
    - name: 1. Wait for any background apt processes to finish
      shell: "while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done"
      changed_when: false

    - name: 2. Update cache with retry
      apt:
        update_cache: yes
      register: apt_res
      until: apt_res is success
      retries: 10
      delay: 5

  roles:
    - role: geerlingguy.nginx
